.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. dork_qt test_dork_qt
clean: FORCE
	$(MAKE) -C .. dork_qt_clean test_dork_qt_clean
check: FORCE
	$(MAKE) -C .. test_dork_qt_check
dork-qt dork-qt.exe: FORCE
	 $(MAKE) -C .. dork_qt
